chore(test): Show failing lint checks
(cherry picked from commit 1531e0e12fe861ff8e1fe758b8113c5d8abae929)

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -84,6 +84,7 @@ jobs:
           done
 
       - name: Lint Check
+        id: lint_check
         if: steps.changed-python-files.outputs.any_changed == 'true'
         env:
           ALL_CHANGED_FILES: ${{ steps.changed-python-files.outputs.all_changed_files }}
@@ -92,6 +93,7 @@ jobs:
         continue-on-error: true
 
       - name: Format Check
+        id: format_check
         if: steps.changed-python-files.outputs.any_changed == 'true'
         env:
           ALL_CHANGED_FILES: ${{ steps.changed-python-files.outputs.all_changed_files }}
@@ -100,12 +102,22 @@ jobs:
         continue-on-error: true
 
       - name: Typing Check
+        id: typing_check
         if: steps.changed-python-files.outputs.any_changed == 'true'
         env:
           ALL_CHANGED_FILES: ${{ steps.changed-python-files.outputs.all_changed_files }}
         run: |
           mypy ${ALL_CHANGED_FILES}
         continue-on-error: true
+
+      - name: Fail if any check failed
+        if: |
+          steps.lint_check.outcome == 'failure' ||
+          steps.format_check.outcome == 'failure' ||
+          steps.typing_check.outcome == 'failure'
+        run: |
+          echo "One or more checks failed."
+          exit 1
 
   semgrep:
     name: Semgrep Rules
@@ -124,7 +136,12 @@ jobs:
     name: Setup Bench
     runs-on: ubuntu-latest
     needs: format
-    if: needs.format.outputs.changed-python == 'true' || needs.format.outputs.changed-json == 'true' || needs.format.outputs.changed-js-vue == 'true' || needs.format.outputs.changed-build == 'true'
+    if: always() && (
+        needs.format.outputs.changed-python == 'true' ||
+        needs.format.outputs.changed-json == 'true' ||
+        needs.format.outputs.changed-build == 'true' ||
+        needs.format.outputs.changed-js-vue == 'true'
+      )
 
     services:
       mariadb:
